[versions]
# Plugins
kotlin = "1.8.21"
android = "8.0.2"
versionUpdater = "0.47.0"
ktlint = "11.4.2"
dokka = "1.8.10"
mavenRelease = "0.25.2"
moshiIR = "0.22.1"
secrets = "2.0.1"

# AndroidX libraries
compatLibrary = "1.6.1"
annotationsLibrary = "1.6.0"
materialLibrary = "1.9.0"
startupLibrary = "1.1.1"
recyclerView = "1.3.0"

# Third party Libraries
googleAdsId = "18.0.1"
retrofit = "2.9.0"
okhttp = "4.11.0"
moshi = "1.15.0"
timber = "5.0.1"
viewBindingProperty = "1.5.9"
coroutines = "1.7.1"

# Test Libraries
junit = "4.13.2"
mockitoKotlin = "5.0.0"
mockitoCore = "5.4.0"

[plugins]
android-library = { id = "com.android.library", version.ref = "android" }
android-app = { id = "com.android.application", version.ref = "android" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
mavenRelease = { id = "com.vanniktech.maven.publish", version.ref = "mavenRelease" }
moshiIR = { id = "dev.zacsweers.moshix", version.ref = "moshiIR"}
android-secrets = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "secrets" }

[libraries]
annotations = { module = "androidx.annotation:annotation", version.ref = "annotationsLibrary" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "compatLibrary" }
material = { module = "com.google.android.material:material", version.ref = "materialLibrary" }
startup = { module = "androidx.startup:startup-runtime", version.ref = "startupLibrary" }
googleAdsId = { module = "com.google.android.gms:play-services-ads-identifier", version.ref = "googleAdsId" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofitConverter = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttpLogging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
viewBindingProperty = { module = "com.github.kirich1409:viewbindingpropertydelegate", version.ref = "viewBindingProperty" }
recyclerView = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerView" }
kotlinCoroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }

kotlinJunit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
mockitoKotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockitoKotlin" }
mockitoCore = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }
junit = { module = "junit:junit", version.ref = "junit" }
okhttpMockServer = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }
